### ISSUE TITLE
Проблема с падингами в секции Цифры

### ISSUE THREAD

**Issue by lexanikitin** [lexanikitin/everland#50]
В разрешениях между десктопом и планшетом у секции нет боковых паддингов, поэтому текст и фотка прилипают к краю экрана. 
<img width="922" alt="image" src="https://user-images.githubusercontent.com/43848156/185387019-351813ee-1d0d-4c79-8b04-a643f31863f2.png">

**Comment by SashkaStudent** [comment]
Контейнер занимает всю ширину экрана из-за некорректного значения в классе .numbers__container
![image](https://user-images.githubusercontent.com/40184171/185569828-7e1d5af9-9541-46e5-bba1-961c0fd05163.png)
