### ISSUE TITLE
Любой интерактивный элемент имеет состояние наведения

### ISSUE THREAD

**Issue by lexanikitin** [lexanikitin/everland#95]
Любой интерактивный элемент имеет состояние наведения, состояние наведения берется из макета или используется прозрачность Комментарий http://joxi.ru/a2Xy4xvfQ6o9DA , http://joxi.ru/12MKWBvCg5o9Er

**Comment by DokKirya** [comment]
В секции истории у дизайнера спрашивали про состояние наведения для ссылок. Ответ был "они не нужны".
