### ISSUE TITLE
 нарушения методологии БЭМ

### ISSUE THREAD

**Issue by lexanikitin** [lexanikitin/everland#98]
5.1 Нет нарушения методологии БЭМ: нет элементов без родительского блока, нет элементов элементов, модификаторы не используются без указания того, что они модифицируют Комментарий Ошибки в БЭМ. http://joxi.ru/1A5e5yVs4M7qZA, http://joxi.ru/DrlPvNjHKl8bPr , http://joxi.ru/eAOaLlvSvBo4pm , Обратите внимание на корректное использование булевого модификатора и модификатора ключ-значение. Например: http://joxi.ru/Y2LL6yvtxBoOj2, http://joxi.ru/Grq61z5izZEKOm Проводите, пожалуйста, самопроверку в https://yoksel.github.io/html-tree/ и https://nglazov.github.io/bem-validator-page/

 5.7 Файловая структура построена по БЭМ nested Ошибки в файловой структуре http://joxi.ru/KAg9Zkjs58x9Nm , http://joxi.ru/vAW1X4ji3doDym, http://joxi.ru/xAelLJVTMNnxb2, http://joxi.ru/gmvZ83Kce4ERQm, http://joxi.ru/KAxRnVatVaEjkm

**Comment by SergeyKukhtalevV** [comment]
Правлю footer и header

**Comment by SashkaStudent** [comment]
Поправил advantages
