### ISSUE TITLE
фиксации высоты для текстовых элементов и блоков

### ISSUE THREAD

**Issue by lexanikitin** [lexanikitin/everland#99]
Использование height и max-height не приводит к выпадению текста или блоков при переполнении Комментарий Все фиксации высоты для текстовых элементов и блоков с динамическим (меняющимся) контентом нужно удалить. Высота блоков "строится" из контента + их отступов. Например: http://joxi.ru/DmBelnvsq7ygar

**Comment by lexanikitin** [comment]
если я правильно понял задумку автора , что макс высота генерится на основании высоты контента в скрипте , то ревьюер ошибся. Тогда стоит подготовить пояснение и опубликуем его для ревьюера.

**Comment by SashkaStudent** [comment]
Для того, чтобы реализовать анимацию плавного открытия/закрытия аккордеона необходимо задавать конкретное значение свойству max-heigth. Данное значение вычисляется в скрипте при открытии/закрытии аккордеона и изменении ширины экрана.
функция `accordionsAdvantages()`.
Внимание на значение `style="max-height"` класса `"accordion__text"`
![accordion](https://user-images.githubusercontent.com/40184171/186031013-79b6f52f-05eb-4d1d-b925-bb80c8fe4a03.gif)

**Comment by lexanikitin** [comment]
перенес комментарий в пуреквест для ревьюера , тикет закрываю
